// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvpzcteslcjkckcphbmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2cHpjdGVzbGNqa2NrY3BoYm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjA4NDAsImV4cCI6MjA3MDIzNjg0MH0._1Ll4Lqp6wvqgkI7h0WadGu2Y5hPZ8Rxo4cwxahwUwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});